apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: nginx
  name: customerdeployment-v1
spec:
  replicas: 2
  selector:
    matchLabels:
      run: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: nginx
    spec:
      containers:
      - image: nginx:alpine
        name: nginx
        ports:
        - containerPort: 6379
        resources: {}
