apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gateway
  name: gateway-v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  strategy: {}
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
        - mountPath: /var/www/html # place index.html
          readOnly: true
          name: index-html
        ports:
        - containerPort: 80
        resources: {}
      volumes:
      - name: index-html
        configMap:
          name: index-html # place ConfigMap `nginx-conf` on /etc/nginx
          items:
            - key: index.html 
              path: index.html
              
