apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gateway
  name: gateway-v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  strategy: {}
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
