apiVersion: v1
kind: Pod
metadata:
  name: initme
spec:
  volumes:
  - name: html
    emptyDir: {}
  containers:
  - name: production
    image: nginx
    volumeMounts:
    - name: html
      mountPath: /var/www/html
  initContainers:
  - name: preproduction
    image: debian
    volumeMounts:
    - name: html
      mountPath: /html
    command: ["/bin/sh", "-c"]
    args:
      - echo "Let's be prepared for prod!" >> /html/index.html

