apiVersion: v1
kind: Service
metadata:
  name: external-db
spec:
  ports:
    -
      name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306 
      nodePort: 0
  selector: {} 

---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-db
subsets: 
- addresses:
  - ip: 192.168.1.14 
  ports:
  - name: mysql
    port: 3306


